info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"

spring:
    profiles:
        active: local

aurora:
  starter:
    headerfilter:
      enabled: false
    token:
        location: /u01/secrets/app/aurora-token/token

logging:
  level:
    no.skatteetaten.aurora.gorg: INFO
    org:
      hibernate: WARN
      springframework: WARN
      apache:
        catalina: WARN
        velocity: WARN

gillis:
    boober:
        url: http://boober
---
spring:
    profiles: local

gillis:
    boober:
        url: http://boober-aurora.utv.paas.skead.no
    username: gillis
    password: gillis

logging:
    pattern:
      console: "%d [%-9.9thread] %highlight(%-5level) %cyan(%logger:%L) %X - %msg %n%rEx{full}"
    # add mokey.openshift.token to ~/.spring-boot-devtools.properties


---
spring:
  profiles: openshift
